FlightCalculator/force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FlightCalculator/force-app/main/default/objects/Flight__c/fields/ArrivalAirport__c.field-meta.xml
<CustomField>
    <fullName>ArrivalAirport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Arrival Airport</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipLabel>Arrival</relationshipLabel>
    <relationshipName>Arrival</relationshipName>
    <type>Lookup</type>
</CustomField>

FlightCalculator/force-app/main/default/objects/Flight__c/fields/DepartureAirport__c.field-meta.xml
<CustomField>
    <fullName>DepartureAirport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure Airport</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipLabel>Departures</relationshipLabel>
    <relationshipName>Departure</relationshipName>
    <type>Lookup</type>
</CustomField>

FlightCalculator/force-app/main/default/objects/Flight__c/fields/FlightDistance__c.field-meta.xml
<CustomField>
    <fullName>FlightDistance__c</fullName>
    <label>Flight distance</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

FlightCalculator/force-app/main/default/classes/FlightSelector.cls
/**
 * Selector class for Flight__c sObject
 * 
 * @author Jakub Dutkiewicz
 * @created 05.10.2022
 */
global inherited sharing class FlightSelector {
    
    private static final List<String> coreFields = new List<String>{
        'Id', 
        'Name',
        'DepartureAirport__c', 
        'ArrivalAirport__c', 
        'FlightDistance__c'
    };

    /**
     * @description Selector method to define populate predefined fields
     * 
     * @author Jakub Dutkiewicz
     * @created 05.10.2022
     * 
     * @return List with field names
     */
    global static List<String> getFlightFields() {
        return coreFields;
    }

    /**
     * @description Selector method to execute query to get all Flight__c sObjects in database
     * 
     * @author Jakub Dutkiewicz
     * @created 05.10.2022
     * 
     * @return List with all Flight__c sObjects
     */
    global static List<Flight__c> getAllFlights() {
        String query = 'SELECT ' + String.join(getFlightFields(), ',') +
            ' FROM Flight__c';
        return Database.query(String.escapeSingleQuotes(query));
    }
}