FlightCalculator/force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FlightCalculator/force-app/main/default/objects/Flight__c/fields/FlightDistance__c.field-meta.xml
<CustomField>
    <fullName>FlightDistance__c</fullName>
    <label>Flight distance</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

FlightCalculator/force-app/main/default/classes/FlightBuilder.cls
/**
 * Builder class for Flight__c sObject
 * 
 * @author Jakub Dutkiewicz
 * @created 04.10.2022
 */
global with sharing class FlightBuilder {
    
    @AuraEnabled 
    global Decimal distance;
    @AuraEnabled 
    global String name;
    @AuraEnabled
    global String departureName;
    @AuraEnabled
    global String arrivalName;

    global FlightBuilder(){}

    /**
     * @description Builder method to copy Flight__c record
     * 
     * @author Jakub Dutkiewicz
     * @created 04.10.2022
     * 
     * @param Flight__c object to be cloned
     * @return cloned Flight__c object
     */
    global FlightBuilder cloneFlight(Flight__c flight) {
        this.distance = flight.FlightDistance__c;
        this.name = flight.Name;
        return this;
    }

    /**
     * @description Builder method to set airports names
     * 
     * @author Jakub Dutkiewicz
     * @created 04.10.2022
     * 
     * @param departureName name of the departure
     * @param arrivalName name of the arrival
     * @return Flight__c object with departure and arrival names
     */
    global FlightBuilder setNamesOnFlight(String departureName, String arrivalName) {
        this.departureName = departureName;
        this.arrivalName = arrivalName;
        return this;
    }

     /**
     * @description Builder method to get FlightBuilder record
     * 
     * @author Jakub Dutkiewicz
     * @created 04.10.2022
     * 
     * @return Flight__c object
     */
    global FlightBuilder getRecord() {
        FlightBuilder flight = new FlightBuilder();
        flight.distance = this.distance;
        flight.name = this.name;
        flight.departureName = this.departureName;
        flight.arrivalName = this.arrivalName;
        return flight;
    }
}