FlightCalculator/force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FlightCalculator/force-app/main/default/objects/Flight__c/fields/ArrivalAirport__c.field-meta.xml
<CustomField>
    <fullName>ArrivalAirport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Arrival Airport</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipLabel>Arrival</relationshipLabel>
    <relationshipName>Arrival</relationshipName>
    <type>Lookup</type>
</CustomField>

FlightCalculator/force-app/main/default/objects/Flight__c/fields/DepartureAirport__c.field-meta.xml
<CustomField>
    <fullName>DepartureAirport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure Airport</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipLabel>Departures</relationshipLabel>
    <relationshipName>Departure</relationshipName>
    <type>Lookup</type>
</CustomField>

FlightCalculator/force-app/main/default/objects/Flight__c/fields/FlightDistance__c.field-meta.xml
<CustomField>
    <fullName>FlightDistance__c</fullName>
    <label>Flight distance</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

FlightCalculator/force-app/main/default/classes/FlightServiceTest.cls
@isTest
public with sharing class FlightServiceTest {
    
    @TestSetup
    static void setupData() {
        TestUtils.addFlight();
    }
    
    @isTest
    public static void calculateFlightTest() {
        List<Flight__c> flightList = [SELECT Id, Name, DepartureAirport__c, ArrivalAirport__c, FlightDistance__c FROM Flight__c];
        List<Airport__c> airportsList = [SELECT Id FROM Airport__c];
        Map<Id, Flight__c> oldFlightIdToFlight = new Map<Id, Flight__c>();

        Decimal startDistance = flightList[0].FlightDistance__c;
        oldFlightIdToFlight.put(flightList[0].Id, flightList[0]);
        flightList[0].DepartureAirport__c = airportsList[2].Id;
        update flightList;

        Test.startTest();
        FlightService.calculateFlights(flightList, oldFlightIdToFlight);
        Test.stopTest();

        List<Flight__c> flightListAfterUpdate = [SELECT Id, Name, DepartureAirport__c, ArrivalAirport__c, FlightDistance__c FROM Flight__c];
        Decimal finalDistance = flightListAfterUpdate[0].FlightDistance__c;

        System.assertNotEquals(finalDistance, startDistance);
    }
}