FlightCalculator/force-app/main/default/objects/Airport__c/fields/IATA__c.field-meta.xml
<CustomField>
    <fullName>IATA__c</fullName>
    <label>IATA</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

FlightCalculator/force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

FlightCalculator/force-app/main/default/objects/Flight__c/fields/ArrivalAirport__c.field-meta.xml
<CustomField>
    <fullName>ArrivalAirport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Arrival Airport</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipLabel>Arrival</relationshipLabel>
    <relationshipName>Arrival</relationshipName>
    <type>Lookup</type>
</CustomField>

FlightCalculator/force-app/main/default/objects/Flight__c/fields/DepartureAirport__c.field-meta.xml
<CustomField>
    <fullName>DepartureAirport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure Airport</label>
    <referenceTo>Airport__c</referenceTo>
    <relationshipLabel>Departures</relationshipLabel>
    <relationshipName>Departure</relationshipName>
    <type>Lookup</type>
</CustomField>

FlightCalculator/force-app/main/default/classes/TestUtils.cls
public with sharing class TestUtils {
    
    public static List<Airport__c> addAirports(Boolean insertToDatabase) {
        Airport__c airportKatowice = new Airport__c(
            IATA__c = 'KTW',
            Geolocation__Latitude__s = 50.270908,
            Geolocation__Longitude__s = 19.039993, 
            Name = 'Katowice'
        );

        Airport__c airportBarcelona = new Airport__c(
            IATA__c = 'BCN',
            Geolocation__Latitude__s = 41.390205,
            Geolocation__Longitude__s = 2.154007, 
            Name = 'Barcelona'
        );

        Airport__c airportNewYork = new Airport__c(
            IATA__c = 'JFK',
            Geolocation__Latitude__s = 40.73061,
            Geolocation__Longitude__s = -73.935242, 
            Name = 'New York'
        );
        List<Airport__c> airports = new List<Airport__c>{airportKatowice, airportBarcelona, airportNewYork};

        if(insertToDatabase){
            insert airports;
        }
        return airports;
    }

    public static Flight__c addFlight(Boolean insertToDatabase) {
        TestUtils.addAirports(true);
        List<Airport__c> airportsList = [SELECT Id FROM Airport__c];
        Flight__c newFlight = new Flight__c(
            Name = 'KTW-BCN',
            DepartureAirport__c = airportsList[0].Id,
            ArrivalAirport__c = airportsList[1].Id
        );

        if(insertToDatabase){
            insert newFlight; 
        }
        return newFlight;
    }
}